name: Feature Request
description: Suggest a new feature or enhancement.
title: "[Feature Request]: "
labels: ["feature request", "enhancement"]
projects: ["maythamfahmi/CryptoNet/2"]
assignees:
  - maythamfahmi
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature or enhancement! Please fill out the following details to help us better understand your request.
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: problem-description
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is. Ex. "I'm always frustrated when [...]"
      placeholder: Describe the problem.
    validations:
      required: true
  - type: textarea
    id: solution-description
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
      placeholder: What would you like to see?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
      placeholder: List any alternative solutions.
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
      placeholder: Provide additional information.
    validations:
      required: false
  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How important is this feature to you?
      options:
        - Low
        - Medium
        - High
        - Critical
      default: 1
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/maythamfahmi/CryptoNet/tree/main/.github/CODE_OF_CONDUCT.md).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
