name: Feature Request
description: Suggest a new feature or enhancement.
title: "[Feature Request]: "
labels: ["feature", "enhancement", "triage"]
projects: ["octo-org/1", "octo-org/44"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature or enhancement!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: Please provide a detailed description of the feature you would like to see.
      placeholder: Describe the feature you'd like to request.
    validations:
      required: true
  - type: textarea
    id: why-needed
    attributes:
      label: Why is this feature needed?
      description: Explain the problem this feature would solve or the improvement it would bring.
      placeholder: Why do you need this feature?
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How important is this feature to you?
      options:
        - Low
        - Medium
        - High
        - Critical
      default: 1
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Possible Alternatives
      description: Have you considered any alternative solutions or workarounds?
      placeholder: List any alternative approaches you've thought of.
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/maythamfahmi/CryptoNet/tree/main/.github/CODE_OF_CONDUCT.md).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
