name: "3. Code Coverage"

permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches:
      - "main"
      - "feature/*"
    paths-ignore:
      - "**/README.md"
      - "coverage-badge.svg"    # prevent loops when the bot updates the badge
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0
          persist-credentials: false   # we'll rely on the action to commit/push

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Install ReportGenerator tool
        run: dotnet tool install --global dotnet-reportgenerator-globaltool

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the solution
        run: dotnet build --no-restore

      - name: Run tests and collect code coverage
        run: dotnet test --no-build --collect:"XPlat Code Coverage"

      - name: Generate code coverage report
        run: reportgenerator -reports:"**/coverage.cobertura.xml" -targetdir:"coverage" -reporttypes:"HtmlInline_AzurePipelines;Badges"

      - name: Upload coverage report zip
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: coverage

      - name: Prepare single-file badge for repo root (only on main)
        if: github.ref == 'refs/heads/main'
        run: |
          cp coverage/badge_linecoverage.svg ./coverage-badge.svg

      # Create/update a PR containing only the badge file. The action handles commits & pushes.
      - name: Open / update PR with coverage badge (only on main)
        if: github.ref == 'refs/heads/main'
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          branch: ci/update-coverage-badge
          base: main
          title: "Update coverage badge"
          commit-message: "Update coverage badge"
          body: "Automated update of coverage-badge.svg"
          add-paths: |
            coverage-badge.svg
          labels: |
            ci
            automated

      - name: Print PR URL
        if: steps.cpr.outputs.pull-request-url
        run: echo "${{ steps.cpr.outputs.pull-request-url }}"
